### ISSUE TITLE
I2C IO Example uses 2 different device addresses?

### ISSUE THREAD

**Issue by ShadowCreator250** [Pi4J/pi4j.github.io#67]
The I2C example at https://www.pi4j.com/documentation/io-examples/i2c/ first uses `i2cdetect` to detect the address as `0x36`.
But the example code below creates the device config with
```java
I2CConfig i2cConfig = I2C.newConfigBuilder(pi4j).id("TCA9534").bus(1).device(0x3f).build();
```
and so uses address `0x3f`.

I assume this code was copied over from https://www.pi4j.com/documentation/providers/linuxfs/. There, the address `0x3f` is used in an example.

Do I understand this correctly as a mistake in the documentation? If not, I think the documentation should explain how we get to the address used in the code.

The relevant source code is found at [content/documentation/io-examples/i2c/_index.md](https://github.com/Pi4J/pi4j.github.io/blob/main/content/documentation/io-examples/i2c/_index.md)

**Comment by eitch** [comment]
Well basically you are right, the addresses aren't the same. But that is ok, since the documentation is correct: You can use i2cdetect to find the address, but most importantly to see if your device is properly connected and communicates its address on the bus. The address of a device is usually also found in the documentation of the device itself.
